import { describe, expect, it } from "vitest";

describe("CAD public API", () => {
  it("exports exactly the documented foundation surface", async () => {
    const api = await import("./index");

    expect(Object.keys(api).sort()).toEqual([
      "ActionReceiptSchema",
      "ActorSchema",
      "ArtifactKindSchema",
      "ArtifactRecordSchema",
      "CadEvaluationEventSchema",
      "CadEvaluationRequestSchema",
      "CadOutputSchema",
      "DefineFrameCommandSchema",
      "DefineParameterCommandSchema",
      "DesignCommandSchema",
      "DesignDocumentContentSchema",
      "DesignDocumentSchema",
      "DesignPreconditionSchema",
      "DesignTransactionSchema",
      "EngineeringJobEventSchema",
      "EngineeringJobKindSchema",
      "EngineeringJobRequestSchema",
      "EngineeringTruthLevelSchema",
      "EntityIdSchema",
      "FrameSchema",
      "ParameterEqualsPreconditionSchema",
      "ParameterSchema",
      "ParameterValueSchema",
      "ReferenceExistsPreconditionSchema",
      "RemoveParameterCommandSchema",
      "RenameDocumentCommandSchema",
      "SemanticReferenceSchema",
      "SetParameterCommandSchema",
      "acceptDesignRevision",
      "applyDesignSessionTransaction",
      "applyDesignTransaction",
      "checkoutDesignRevision",
      "childRevisions",
      "commitDesignRevision",
      "createArtifactIndex",
      "createDesignDocument",
      "createDesignHistory",
      "createDesignSession",
      "defineActionReceipt",
      "defineArtifactRecord",
      "defineCadEvaluationRequest",
      "defineDesignDocument",
      "inspectDesignSession",
      "invalidateArtifacts",
      "parentRevision",
    ]);
  });
});
